### ISSUE TITLE
False positive in racy-append-to-slice

### ISSUE THREAD

**Issue by geniass** [trailofbits/semgrep-rules#16]
Hi,

I believe I have come across another false positive in racy-append-to-slice.
Please see the [linked example](https://semgrep.dev/s/zANd)

I'm not very familiar with semgrep rules but it seems like the `...` placeholder might not be specific enough, because it seems to detect the "append" pattern anywhere in the vicinity of a goroutine in a for loop.

**Comment by hex0punk** [comment]
Thank you for opening up this issue, @geniass. We will start looking into it and will come up with a solution
