### ISSUE TITLE
Enhance github actions

### ISSUE THREAD

**Issue by GrosQuildu** [trailofbits/semgrep-rules#20]
* run [semgrep's linters](https://semgrep.dev/p/semgrep-rule-lints) with `semgrep --validate`
* run [checks for metadata](https://github.com/returntocorp/semgrep-rules/blob/develop/.github/workflows/validate-r2c-registry-metadata.yaml)
* maybe run performance tests
* maybe make use of https://github.com/returntocorp/semgrep-rules-test-action/

**Comment by Vasco-jofra** [comment]
I also noticed that the `semgrep --test` workflow is incorrect. 

https://github.com/trailofbits/semgrep-rules/blob/f0dfa238a0c8aed1ae5672cdfadb43f387462595/.github/workflows/semgrep-rules-test.yml#L27-L29

It does `semgrep --test rust/`, but the folder is called `rs/`. We should probably just do `semgrep --test /` to test everything, or use an existing action as you suggest.

**Comment by GrosQuildu** [comment]
Resolved in https://github.com/trailofbits/semgrep-rules/pull/40
