### ISSUE TITLE
`missing-runlock-on-rwmutex` and `missing-unlock-before-return` false positives

### ISSUE THREAD

**Issue by Vasco-jofra** [trailofbits/semgrep-rules#57]
The [`missing-runlock-on-rwmutex`](https://github.com/trailofbits/semgrep-rules/blob/main/go/missing-runlock-on-rwmutex.yaml) rule has FPs when the unlock pattern is:
```go
unlockFunction := lock.RUnlock
defer func() {
	unlockFunc()
}()
```

**Comment by Vasco-jofra** [comment]
Same for:
```go
releaseLock := lock.RUnlock
a, err := asd()
if err != nil {
    releaseLock()
    return nil, err
}
```

**Comment by GrosQuildu** [comment]
Based on short experiments, it may be hard to fix.
* Semgrep does not support functions as typed metavariables (or I could not get it to work) - no way to have one variable `$U` that will match `$T.RUnlock` directly and through variable.
* we could have `pattern-either` with one case for direct calls to `RUnlock` and second case for calls via variable. I had problem writing a match for function assignment and later call. Maybe semgrep does not handle this well, or I made mistakes
* maybe data flow can help here?
