### ISSUE TITLE
False positive for racy-append-to-slice

### ISSUE THREAD

**Issue by mihaitodor** [trailofbits/semgrep-rules#8]
Nice project, thanks for making these rules available! It looks like https://github.com/trailofbits/semgrep-rules/blob/main/go/racy-append-to-slice.yml should take locking via mutex around `append` into account. It gives a false positive for [this](https://github.com/Jeffail/benthos/blob/7a84f39f6e6f8cce59aa44456d5b3db375f6e639/lib/service/lint.go#L189-L191).

**Comment by hex0punk** [comment]
Thank you for opening this issue @mihaitodor. Closing this as it is solved by PR #10

**Comment by mihaitodor** [comment]
Thank you for fixing it!
